language: ruby
dist: bionic
sudo: false
cache: bundler
script: bundle exec rspec
bundler_args: --without=extras
before_script:
  - bundle exec sidekiq -r ./spec/dummy_app/app.rb -L /tmp/sidekiq.log &
  - sleep 1
services:
  - redis-server
rvm:
  - 2.5.7
  - 2.6.5
  - jruby-9.2.9.0
  - 2.7.3
  - 3.0.4
  - 3.1.2
